# Note: May need to install MySQL-python on Fedora
---
- hosts:
  - <webapp_host> # Change this
  - <db_host>     # Change this
  any_errors_fatal: true
  vars_prompt:
    - name: "new_password"
      prompt: "New User Password"
    - name: "root_mysql_password"
      prompt: "Database Root Password"
  tasks:
  - set_fact:
      new_password: "{{new_password}}"
      root_mysql_password: "{{root_mysql_password}}"

- hosts: <db_host>   # Change this
  tasks:
  - mysql_user:
      login_user: root
      login_password: "{{root_mysql_password}}"
      name: <webapp_username>                 # Change this
      host_all: yes
      password: "{{new_password}}"

- hosts: <webapp_host> # Change this
  tasks:
  - lineinfile:
      name: /var/www/webapp/config.something    # Change this
      regexp: "^mysql_password:"                # Change this
      line: "mysql_password: {{new_password}}"  # Change this


