---
- name: "SCORED | 4.1.1.1 | PATCH | Ensure auditd is installed"
  block:
      - name: "SCORED | 4.1.1.1 | PATCH | Ensure auditd is installed | Check for auditd packages"
        command: rpm -q audit audit-libs
        become: true
        failed_when: no
        changed_when: no
        register: rhel8cis_4_1_1_1_auditdpackages

      - name: "SCORED | 4.1.1.1 | PATCH | Ensure auditd is installed | Install auditd packages"
        dnf:
            name: audit
            state: present
        become: true
        when:
            - '"package audit is not installed" in rhel8cis_4_1_1_1_auditdpackages.stdout'

      - name: "SCORED | 4.1.1.1 | PATCH | Ensure auditd is installed | Install auditd-lib packages"
        dnf:
            name: audit-libs
            state: present
        become: true
        when:
            - '"audit-libs-" not in rhel8cis_4_1_1_1_auditdpackages.stdout'
  when:
      - rhel8cis_rule_4_1_1_1
  tags:
      - level2
      - patch
      - rule_4.1.1.1

- name: "SCORED | 4.1.1.2 | PATCH | Ensure auditd service is enabled"
  service:
      name: auditd
      state: started
      enabled: yes
  when:
      - not rhel8cis_skip_for_travis
      - rhel8cis_rule_4_1_1_2
      - ansible_connection != 'docker'
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.2

- name: "SCORED | 4.1.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
      replace: '\1"\2 audit=1"'
      follow: yes
  ignore_errors: yes
  notify: generate new grub config
  when:
      - rhel8cis_rule_4_1_1_3
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.3

- name: "SCORED | 4.1.1.4 | PATCH | Ensure audit_backlog_limit is sufficient"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit_backlog_limit={{ rhel8cis_audit_back_log_limit }})(?:")'
      replace: '\1"\2 audit_backlog_limit={{ rhel8cis_audit_back_log_limit }}"'
      follow: yes
  ignore_errors: yes
  become: true
  when:
      - rhel8cis_rule_4_1_1_4
  tags:
      - level2
      - patch
      - rule_4.1.1.4

- name: "SCORED | 4.1.2.1 | PATCH | Ensure audit log storage size is configured"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file( |=)"
      line: "max_log_file = {{ rhel8cis_max_log_file_size }}"
      state: present
  when:
      - rhel8cis_rule_4_1_2_1
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.2.1

- name: "SCORED | 4.1.2.2 | PATCH | Ensure audit logs are not automatically deleted"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file_action"
      line: "max_log_file_action = {{ rhel8cis_auditd['max_log_file_action'] }}"
      state: present
  when:
      - rhel8cis_rule_4_1_2_2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.2.2

- name: "SCORED | 4.1.2.3 | PATCH | Ensure system is disabled when audit logs are full"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^admin_space_left_action"
      line: "admin_space_left_action = {{ rhel8cis_auditd['admin_space_left_action'] }}"
      state: present
  when:
      - rhel8cis_rule_4_1_2_3
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.2.3

- name: "SCORED | 4.1.3 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  template:
      src: audit/rhel8cis_rule_4_1_3.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_3.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_3
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.3

- name: "SCORED | 4.1.4 | PATCH | Ensure login and logout events are collected"
  template:
      src: audit/rhel8cis_rule_4_1_4.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_4.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_4
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.4

- name: "SCORED | 4.1.5 | PATCH | Ensure session initiation information is collected"
  template:
      src: audit/rhel8cis_rule_4_1_5.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_5.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_5
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.5

- name: "SCORED | 4.1.6 | PATCH | Ensure events that modify date and time information are collected"
  template:
      src: audit/rhel8cis_rule_4_1_6.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_6.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_6
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.6

- name: "SCORED | 4.1.7 | PATCH | Ensure events that modify the system's Mandatory Access Controls are collected"
  template:
      src: audit/rhel8cis_rule_4_1_7.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_7.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_7
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.7

- name: "SCORED | 4.1.8 | PATCH | Ensure events that modify the system's network environment are collected"
  template:
      src: audit/rhel8cis_rule_4_1_8.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_8.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_8
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.8

- name: "SCORED | 4.1.9 | PATCH | Ensure discretionary access control permission modification events are collected"
  template:
      src: audit/rhel8cis_rule_4_1_9.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_9.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_9
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.9

- name: "SCORED | 4.1.10 | PATCH | Ensure unsuccessful unauthorized file access attempts are collected"
  template:
      src: audit/rhel8cis_rule_4_1_10.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_10.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_10
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.10

- name: "SCORED | 4.1.11 | PATCH | Ensure events that modify user/group information are collected"
  template:
      src: audit/rhel8cis_rule_4_1_11.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_11.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_11
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.11

- name: "SCORED | 4.1.12 | PATCH | Ensure successful file system mounts are collected"
  block:
      - name: "SCORED | 4.1.12 | PATCH | Ensure successful file system mounts are collected"
        shell: for i in  $(df | grep '^/dev' | awk '{ print $NF }'); do find $i -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null; done
        register: priv_procs
        changed_when: no
        check_mode: no

      - name: "SCORED | 4.1.12 | PATCH | Ensure successful file system mounts are collected"
        template:
            src: audit/rhel8cis_rule_4_1_12.rules.j2
            dest: /etc/audit/rules.d/rhel8cis_rule_4_1_12.rules
            owner: root
            group: root
            mode: 0600
        notify: restart auditd
  when:
      - rhel8cis_rule_4_1_12
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.12

- name: "SCORED | 4.1.13 | PATCH | Ensure use of privileged commands is collected"
  template:
      src: audit/rhel8cis_rule_4_1_13.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_13.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_13
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.13

- name: "SCORED | 4.1.14 | PATCH | Ensure file deletion events by users are collected"
  template:
      src: audit/rhel8cis_rule_4_1_14.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_14.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_14
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.14

- name: "SCORED | 4.1.15 | PATCH | Ensure kernel module loading and unloading is collected"
  template:
      src: audit/rhel8cis_rule_4_1_15.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_15.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_15
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.15

- name: "SCORED | 4.1.16 | PATCH | Ensure system administrator actions (sudolog) are collected"
  template:
      src: audit/rhel8cis_rule_4_1_16.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_16.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_16
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.16

- name: "SCORED | 4.1.17 | PATCH | Ensure the audit configuration is immutable"
  template:
      src: audit/rhel8cis_rule_4_1_17.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_17.rules
      owner: root
      group: root
      mode: 0600
  when:
      - rhel8cis_rule_4_1_17
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.17

- name: "SCORED | 4.2.1.1 | PATCH | Ensure rsyslog or syslog-ng is installed"
  dnf:
      name: "{{ rhel8cis_syslog }}"
      state: present
  when:
      - rhel8cis_rule_4_2_1_1
  tags:
      - level1
      - patch
      - rule_4.2.1.1

- name: "SCORED | 4.2.1.2 | PATCH | Ensure rsyslog Service is enabled"
  service:
      name: rsyslog
      enabled: yes
  when:
      - rhel8cis_rule_4_2_1_2
      - rhel8cis_syslog == 'rsyslog'
  tags:
      - level1
      - patch
      - rsyslog
      - rule_4.2.1.2

- name: "SCORED | 4.2.1.3 | PATCH | Ensure rsyslog default file permissions configured"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode'
      line: '$FileCreateMode 0640'
  notify: restart rsyslog
  when:
      - rhel8cis_rule_4_2_1_3
  tags:
      - level1
      - patch
      - rule_4.2.1.3

- name: "NOTSCORED | 4.2.1.4 | PATCH | Ensure logging is configured"
  block:
      - name: "NOTSCORED | 4.2.1.4 | AUDIT | Ensure logging is configured | rsyslog current config message out"
        command: cat /etc/rsyslog.conf
        become: yes
        changed_when: false
        failed_when: no
        register: rhel_08_4_2_1_4_audit
      - debug:
            msg:
                - "These are the current logging configurations for rsyslog, please review:"
                - "{{ rhel_08_4_2_1_4_audit.stdout_lines }}"

      - name: "NOTSCORED | 4.2.1.4 | PATCH | Ensure logging is configured | mail.* log setting"
        lineinfile:
            path: /etc/rsyslog.conf
            state: present
            regexp: '^mail\.\*(.*)$'
            marker: "# {mark} MAIL LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
                # mail logging additions to meet CIS standards
                mail.*                                                  -/var/log/mail
                mail.info                                               -/var/log/mail.info
                mail.warning                                            -/var/log/mail.warning
                mail.err                                                /var/log/mail.err
            insertafter: '# Log all the mail messages in one place.'
        notify: restart rsyslog
        when:
            - rhel8cis_rsyslog_ansibleManaged

      - name: "NOTSCORED | 4.2.1.4 | PATCH | Ensure logging is configured | news.crit log setting"
        lineinfile:
            path: /etc/rsyslog.conf
            state: present
            regexp: '^news\.\crit(.*)$'
            marker: "# {mark} NEWS LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
                # news logging additions to meet CIS standards
                news.crit                                               -/var/log/news/news.crit
                news.notice                                             -/var/log/news/news.crit
            insertafter: '# Save news errors of level crit and higher in a special file.'
        notify: restart rsyslog
        when:
            - rhel8cis_rsyslog_ansibleManaged

      - name: "NOTSCORED | 4.2.1.4 | PATCH | Ensure logging is configured | Misc. log setting"
        blockinfile:
            path: /etc/rsyslog.conf
            state: present
            regexp: '^news\.\notice(.*)$'
            marker: "# {mark} MISC. LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
                # misc. logging additions to meet CIS standards
                *.=warning;*.=err                                        -/var/log/warn
                *.crit                                                   /var/log/warn
                *.*;mail.none;news.none                                  /var/log/messages
            insertafter: '#### RULES ####'
        notify: restart rsyslog
        when:
            - rhel8cis_rsyslog_ansibleManaged

      - name: "NOTSCORED | 4.2.1.4 | PATCH | Ensure logging is configured | Local log settings"
        blockinfile:
            path: /etc/rsyslog.conf
            state: present
            regexp: '^news\.\notice(.*)$'
            marker: "#{mark} LOCAL LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
                # local log settings
                local0,local1.*                                          -/var/log/localmessages
                local2,local3.*                                          -/var/log/localmessages
                local4,local5.*                                          -/var/log/localmessages
                local6,local7.*                                          -/var/log/localmessages
                *.emrg                                                    :omusrmsg:*
            insertafter: '#### RULES ####'
        notify: restart rsyslog
  when:
      - rhel8cis_rule_4_2_1_4
  tags:
      - level1
      - patch
      - rsyslog
      - rule_4.2.1.4

- name: "SCORED | 4.2.1.5 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  blockinfile:
      path: /etc/rsyslog.conf
      state: present
      block: |
          # remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
          *.* @@{{ rhel8cis_remote_log_server }}
      insertafter: EOF
  register: result
  failed_when:
      - result is failed
      - result.rc != 257
  notify: restart rsyslog
  when:
      - rhel8cis_rule_4_2_1_5
      - rhel8cis_remote_log_server is defined
  tags:
      - level1
      - patch
      - rule_4.2.1.5
      - rsyslog

- name: "NOTSCORED | 4.2.1.6 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
  block:
      - name: "NOTSCORED | 4.2.1.6 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts. | When not log host"
        replace:
            path: /etc/rsyslog.conf
            regexp: '({{ item }})'
            replace: '#\1'
        with_items:
            - '^(\$ModLoad imtcp)'
            - '^(\$InputTCPServerRun)'
        notify: restart rsyslog
        when:
            - not rhel8cis_system_is_log_server

      - name: "NOTSCORED | 4.2.1.6 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts. | When log host"
        replace:
            path: /etc/rsyslog.conf
            regexp: '^#(.*{{ item }}.*)'
            replace: '\1'
        with_items:
            - 'ModLoad imtcp'
            - 'InputTCPServerRun'
        notify: restart rsyslog
        when:
            - rhel8cis_system_is_log_server
  when:
      - rhel8cis_rule_4_2_1_6
  tags:
      - level1
      - patch
      - rule_4.2.1.6
      - rsyslog

- name: "SCORED | 4.2.2.1 | PATCH | Ensure journald is configured to send logs to rsyslog"
  lineinfile:
      dest: /etc/systemd/journald.conf
      regexp: "^#ForwardToSyslog=|^ForwardToSyslog="
      line: ForwardToSyslog=yes
      state: present
  become: true
  when:
      - rhel8cis_rule_4_2_2_1
  tags:
      - level1
      - patch
      - rule_4.2.2.1

- name: "SCORED | 4.2.2.2 | PATCH | Ensure journald is configured to compress large log files"
  lineinfile:
      dest: /etc/systemd/journald.conf
      regexp: "^#Compress=|^Compress="
      line: Compress=yes
      state: present
  become: true
  when:
      - rhel8cis_rule_4_2_2_2
  tags:
      - level1
      - patch
      - rule_4.2.2.2

- name: "SCORED | 4.2.2.3 | PATCH | Ensure journald is configured to write logfiles to persistent disk"
  lineinfile:
      dest: /etc/systemd/journald.conf
      regexp: "^#Storage=|^Storage="
      line: Storage=persistent
      state: present
  become: true
  when:
      - rhel8cis_rule_4_2_2_3
  tags:
      - level1
      - patch
      - rule_4.2.2.3

- name: "SCORED | 4.2.3 | PATCH | Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx {} + -o -type d -exec chmod g-w,o-rwx "{}" +
  changed_when: no
  failed_when: no
  when:
      - rhel8cis_rule_4_2_3
  tags:
      - level1
      - patch
      - rule_4.2.3

- name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
  block:
      - name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured | Get logrotate settings"
        find:
            paths: /etc/logrotate.d/
        register: log_rotates

      - name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
        replace:
            path: "{{ item.path }}"
            regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
            replace: "\\1{{ rhel8cis_logrotate }}"
        with_items:
            - "{{ log_rotates.files }}"
            - { path: "/etc/logrotate.conf" }
  when:
      - rhel8cis_rule_4_3
  tags:
      - level1
      - patch
      - rule_4.3
